# used to store secret env variables
# do not put secret files in vcs
apiVersion: v1
kind: secret
type: Opaque
metadata:
  name: agent-cli-secret
data:
  GEMINI_API_KEY: "[GEMINI_API_KEY]"
  TELEGRAM_BOT_TOKEN: "[TELEGRAM_BOT_TOKEN]"
